### ISSUE TITLE
Pulldown handle in 1.1.6 with bootstrap 2 is rendered incorrectly

### ISSUE THREAD

**Issue by lphooge** [danielfarrell/bootstrap-combobox#181]
It seems to miss the button-styles (looks flat), the caret is misaligned und the clear-icon is always visible.
See attached screenshot
![bildschirmfoto 2015-05-05 um 17 05 29](https://cloud.githubusercontent.com/assets/1904057/7475833/3f250928-f34a-11e4-853f-0ef2be9b1a8c.png)

**Comment by pmorch** [comment]
I can confirm this. Also that it worked in 1.1.5, but not in 1.1.6 and bootstrap (either 2.3.0 or 2.3.2)

**Comment by pmorch** [comment]
I've found a CSS workaround: I added this to our page, and now 1.1.6 works with bootstrap 2.3.2:

```css
<style>
    /*
        This fixes issue:
        "Pulldown handle in 1.1.6 with bootstrap 2 is rendered incorrectly"
        https://github.com/danielfarrell/bootstrap-combobox/issues/181

        I addition to the i.icon-remove to being shown when something has
        been selected, the vertical placements of the caret and icon-remove
        needed adjusting.

            margin-top: <constant>px

        Is perhaps not a good solution, but it works for me.
    */
    div.combobox-container i.icon-remove {
        display: none;
    }
    div.combobox-container.combobox-selected i.icon-remove {
        display: block;
        margin-top: 4px;
    }
    div.combobox-container span.caret {
        margin-top: 8px;
    }
</style>
```
